drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
drop table if exists comment cascade
drop table if exists post cascade
drop table if exists post_image cascade
